# Generated by Django 5.0.2 on 2024-04-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='created_date',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='is_admin',
            new_name='is_active',
        ),
    ]
