# Generated by Django 5.0.2 on 2024-04-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
